services:
  portfolio:
    build: .
    container_name: portfolio_dev

    ports:
      - "5173:5173"

    volumes:
      - .:/app
      - /app/node_modules

    environment:
      - VITE_GITHUB_TOKEN=${VITE_GITHUB_TOKEN}
